import {
  type LucideIcon,
  Activity,
  ArrowLeft,
  ArrowRight,
  AtSign,
  Award,
  BadgeCheck,
  Ban,
  Banknote,
  Battery,
  BatteryCharging,
  Bell,
  Boxes,
  Building,
  Cable,
  Calendar,
  ChartColumn,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  CircleAlert,
  CircleCheck,
  CircleDashed,
  CircleDot,
  CircleQuestionMark,
  CircleX,
  ClipboardCheck,
  ClipboardList,
  Clock,
  CloudOff,
  Code,
  Coins,
  Compass,
  Copy,
  Cpu,
  CreditCard,
  Crosshair,
  Database,
  Download,
  Ellipsis,
  EllipsisVertical,
  ExternalLink,
  Eye,
  Factory,
  FileText,
  Flag,
  Flame,
  Folder,
  FolderOpen,
  Fan,
  Gauge,
  Globe,
  Hammer,
  HardHat,
  Hash,
  Heart,
  HeartPulse,
  Highlighter,
  House,
  Hourglass,
  Image,
  Inbox,
  Info,
  KeyRound,
  Layers,
  LayoutDashboard,
  Lightbulb,
  Link,
  Link2,
  ListChecks,
  ListFilter,
  Lock,
  LogIn,
  LogOut,
  Mail,
  Map,
  MapPin,
  Menu,
  MessageCircle,
  MessageSquare,
  MessagesSquare,
  Microscope,
  Minus,
  NotebookPen,
  OctagonAlert,
  Palette,
  PenLine,
  Pencil,
  PenTool,
  Phone,
  Plug,
  PlugZap,
  Plus,
  Printer,
  Puzzle,
  QrCode,
  Receipt,
  RefreshCw,
  Reply,
  Rocket,
  RotateCw,
  Ruler,
  Scale,
  Scan,
  ScrollText,
  Search,
  Send,
  Settings,
  Share2,
  ShieldCheck,
  ShieldHalf,
  ShoppingBag,
  ShoppingCart,
  Sparkle,
  Sparkles,
  Star,
  Store,
  Tag,
  Target,
  TestTube,
  ThumbsUp,
  Thermometer,
  Timer,
  Toolbox,
  Trash,
  TrendingUp,
  Truck,
  TriangleAlert,
  Undo,
  Unlink,
  Upload,
  User,
  UserPlus,
  UserRound,
  Users,
  Utensils,
  Wallet,
  WavesHorizontal,
  Wrench,
  X,
  Zap,
} from 'lucide-react'

/**
 * ثبت آیکون‌های پلتفرم بساز — تنها منبع آیکون‌های SVG.
 *
 * قاعده: از ایموجی به‌جای آیکون استفاده نکنید.
 *   درست:   <Ic name="wrench" className="size-4" />
 *   درست:   <Ic name={CATEGORY_ICONS[recipe.category]} />
 *   غلط:    <span>🔧</span>
 */
export const ICONS = {
  /* ---- ناوبری و عمومی ---- */
  home: House,
  search: Search,
  menu: Menu,
  close: X,
  check: Check,
  plus: Plus,
  minus: Minus,
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  externalLink: ExternalLink,
  download: Download,
  upload: Upload,
  copy: Copy,
  info: Info,
  bell: Bell,
  tag: Tag,
  layers: Layers,
  ellipsis: Ellipsis,
  ellipsisVertical: EllipsisVertical,
  filter: ListFilter,
  eye: Eye,
  trash: Trash,
  edit: PenLine,
  pencil: Pencil,
  refresh: RefreshCw,
  rotate: RotateCw,
  undo: Undo,
  share: Share2,
  link: Link,
  link2: Link2,
  unlink: Unlink,
  send: Send,
  print: Printer,
  scan: Scan,
  qr: QrCode,
  hash: Hash,
  at: AtSign,

  /* ---- حساب و نقش‌ها ---- */
  user: User,
  userRound: UserRound,
  users: Users,
  userPlus: UserPlus,
  login: LogIn,
  logout: LogOut,
  lock: Lock,
  key: KeyRound,
  settings: Settings,
  badgeCheck: BadgeCheck,
  shield: ShieldCheck,
  shieldHalf: ShieldHalf,
  clipboardCheck: ClipboardCheck,

  /* ---- محتوا و پروژه ---- */
  clipboard: ClipboardList,
  file: FileText,
  notebook: NotebookPen,
  folder: Folder,
  folderOpen: FolderOpen,
  scroll: ScrollText,
  dashboard: LayoutDashboard,
  list: ListChecks,
  inbox: Inbox,
  calendar: Calendar,
  clock: Clock,
  timer: Timer,
  hourglass: Hourglass,

  /* ---- مالی ---- */
  wallet: Wallet,
  coins: Coins,
  banknote: Banknote,
  cart: ShoppingCart,
  bag: ShoppingBag,
  receipt: Receipt,
  creditCard: CreditCard,
  scale: Scale,

  /* ---- ساخت و صنعت ---- */
  wrench: Wrench,
  hammer: Hammer,
  toolbox: Toolbox,
  hardHat: HardHat,
  factory: Factory,
  store: Store,
  building: Building,
  truck: Truck,

  /* ---- الکترونیک و قطعات ---- */
  zap: Zap,
  plug: Plug,
  plugZap: PlugZap,
  battery: Battery,
  batteryCharging: BatteryCharging,
  circuit: Cpu,
  code: Code,
  lightbulb: Lightbulb,
  fan: Fan,
  thermometer: Thermometer,
  waves: WavesHorizontal,
  circleDot: CircleDot,
  circleDashed: CircleDashed,
  puzzle: Puzzle,
  cable: Cable,
  boxes: Boxes,

  /* ---- دسته‌بندی دستورها ---- */
  microscope: Microscope,
  testTube: TestTube,
  gauge: Gauge,
  activity: Activity,
  flame: Flame,

  /* ---- وضعیت و پیام ---- */
  alert: TriangleAlert,
  alertCircle: CircleAlert,
  alertOctagon: OctagonAlert,
  circleCheck: CircleCheck,
  circleX: CircleX,
  circleQuestion: CircleQuestionMark,
  ban: Ban,
  cloudOff: CloudOff,
  trendingUp: TrendingUp,
  chart: ChartColumn,
  target: Target,
  rocket: Rocket,
  sparkles: Sparkles,
  sparkle: Sparkle,

  /* ---- ارتباطی ---- */
  message: MessageSquare,
  messageCircle: MessageCircle,
  messages: MessagesSquare,
  mail: Mail,
  phone: Phone,
  globe: Globe,
  map: Map,
  mapPin: MapPin,
  flag: Flag,
  compass: Compass,
  crosshair: Crosshair,
  reply: Reply,

  /* ---- امتیاز و تعامل ---- */
  star: Star,
  heart: Heart,
  heartPulse: HeartPulse,
  thumbsUp: ThumbsUp,
  award: Award,
  palette: Palette,
  penTool: PenTool,
  highlighter: Highlighter,
  ruler: Ruler,
  image: Image,
  database: Database,
  utensils: Utensils,
  circle: Circle,
} satisfies Record<string, LucideIcon>

export type IconName = keyof typeof ICONS

/**
 * کامپوننت آیکون — نام‌ها را از `ICONS` می‌خواند و در صورت ناشناخته بودن دایرهٔ خنثی نشان می‌دهد.
 */
export function Ic({
  name,
  size = 18,
  className,
  strokeWidth = 2,
}: {
  name: IconName | string
  size?: number
  className?: string
  strokeWidth?: number
}) {
  const Icon = (ICONS as Record<string, LucideIcon>)[name] ?? Circle
  return (
    <Icon
      size={size}
      strokeWidth={strokeWidth}
      className={className}
      aria-hidden="true"
      focusable="false"
    />
  )
}

/* ------------------------------------------------------------------ */
/* نگاشت‌های معنایی — برای دسته‌بندی‌ها، نقش‌ها و وضعیت‌ها             */
/* ------------------------------------------------------------------ */

/** دسته‌بندی دستورهای ساخت */
export const CATEGORY_ICONS: Record<string, IconName> = {
  lighting: 'lightbulb',
  power: 'batteryCharging',
  cooling: 'fan',
  testing: 'microscope',
}

export const CATEGORY_LABELS: Record<string, string> = {
  lighting: 'روشنایی',
  power: 'توان',
  cooling: 'خنک‌کننده',
  testing: 'تست',
}

/** دسته‌بندی قطعات کاتالوگ */
export const PART_CATEGORY_ICONS: Record<string, IconName> = {
  led: 'lightbulb',
  resistor: 'circuit',
  cable: 'plug',
  switch: 'circleDot',
  battery: 'batteryCharging',
  protection: 'shield',
  converter: 'zap',
  charger: 'plugZap',
  enclosure: 'boxes',
  wire: 'waves',
  fan: 'fan',
  holder: 'boxes',
}

/** نقش‌های کاربری */
export const ROLE_ICONS: Record<string, IconName> = {
  Guest: 'user',
  Member: 'userRound',
  Engineer: 'wrench',
  SafetyReviewer: 'shield',
  Supplier: 'store',
  Maker: 'hardHat',
  Admin: 'settings',
}

/** آیکون لینک‌های سریع پروفایل بر اساس نقش */
export const LINK_ICONS: Record<string, IconName> = {
  recipes: 'clipboard',
  parts: 'puzzle',
  makers: 'factory',
  wizard: 'sparkles',
  projects: 'folder',
  dashboard: 'chart',
  jobs: 'hammer',
  services: 'toolbox',
  users: 'users',
  orders: 'cart',
  suppliers: 'store',
}
